mybats:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mappers/*Mapper.xml
  # 如果是放在resource目录 classpath:/mappers/*Mapper.xml
  mapper-locations: classpath:com/study/demo/*/dao/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.study.demo.*.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql