db: biu
server:
  port: 8080
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID

spring:
  profiles:
    active: dev
    include: druid,mybatis
  messages:
    encoding: UTF-8
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${db}?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Root@123456
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  path: ./logs
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.study.demo: debug
