db: biu
db-slave1: biu_s1
db-slave2: biu_s2
Spring:
  datasource:
    master:
      #driver: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/${db}?characterEncoding=UTF-8&useSSL=false
      username: root
      password: Root@123456
      type: com.alibaba.druid.pool.DruidDataSource
    cluster:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/${db-slave1}?characterEncoding=UTF-8&useSSL=false
      username: root
      password: Root@123456
      type: com.alibaba.druid.pool.DruidDataSource
