db: biu
Spring:
  datasource:
    master:
      #driver: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/${db}?characterEncoding=UTF-8&useSSL=false
      username: root
      password: Root@123456
    slave:
      #driver: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/${db}?characterEncoding=UTF-8&useSSL=false
      username: root
      password: Root@123456
